### ISSUE TITLE
HELP: OccludedFunction not working in ISPC mode

### ISSUE THREAD

**Issue by rt258** [embree/embree-renderer#5]
Dear all,

 I have a problem to invoke OccludedFunction() when coding in ISPC mode. 
After I defined my OccludedFunction(), I use rtcSetOccludedFunction and then the rtcOccleded() should invoke my OccludedFunction (this works fine in C++ mode), however, in this just doesn't work in ISPC. 

Does anyone have the same problem before, or how could I fix this?

**Here is the code:**
In C++ (working):
	void occlusionFilter(void* ptr, Ray& ray)
	{
		ray.id0 = -1;
	}

	BBox3f TriangleMeshFull::extract(RTCScene scene, size_t id) const
	{
		BBox3f bounds = empty;
		size_t numTimeSteps = motion.size() ? 2 : 1;
		unsigned mesh = rtcNewTriangleMesh(scene, RTC_GEOMETRY_STATIC, triangles.size(), position.size(), numTimeSteps);
		if (mesh != id) throw std::runtime_error("ID does not match");

		/* copy indices */
		RTCTriangle* triangles_o = (RTCTriangle*)rtcMapBuffer(scene, mesh, RTC_INDEX_BUFFER);
		for (size_t j = 0; j < triangles.size(); j++) {
			const TriangleMeshFull::Triangle& tri = triangles[j];
			triangles_o[j].v0 = tri.v0;
			triangles_o[j].v1 = tri.v1;
			triangles_o[j].v2 = tri.v2;
		}
		rtcUnmapBuffer(scene, mesh, RTC_INDEX_BUFFER);

		if (motion.size())
		{
			Vec3fa* vertices0_o = (Vec3fa*)rtcMapBuffer(scene, mesh, RTC_VERTEX_BUFFER0);
			Vec3fa* vertices1_o = (Vec3fa*)rtcMapBuffer(scene, mesh, RTC_VERTEX_BUFFER1);
			for (size_t j = 0; j < position.size(); j++) {
				const Vector3f p0 = position[j];
				const Vector3f p1 = p0 + motion[j];
				vertices0_o[j].x = p0.x;
				vertices0_o[j].y = p0.y;
				vertices0_o[j].z = p0.z;
				vertices1_o[j].x = p1.x;
				vertices1_o[j].y = p1.y;
				vertices1_o[j].z = p1.z;
				bounds.grow(p0);
				bounds.grow(p1);
			}
			rtcUnmapBuffer(scene, mesh, RTC_VERTEX_BUFFER0);
			rtcUnmapBuffer(scene, mesh, RTC_VERTEX_BUFFER1);
		}
		else
		{
			Vec3fa* vertices_o = (Vec3fa*)rtcMapBuffer(scene, mesh, RTC_VERTEX_BUFFER);
			for (size_t j = 0; j < position.size(); j++) {
				const Vector3f p = position[j];
				vertices_o[j].x = p.x;
				vertices_o[j].y = p.y;
				vertices_o[j].z = p.z;
				bounds.grow(p);
			}
			rtcUnmapBuffer(scene, mesh, RTC_VERTEX_BUFFER);
		}

		if (1) {
			rtcSetOcclusionFilterFunction(scene, mesh, (RTCFilterFunc)&occlusionFilter);
		}
		return bounds;
	}

In ISPC (not working):
void occlusionFilterMy(void* uniform ptr, varying RTCRay& ray)
{
	print("occlusion");
	ray.id0 = -1;
}

uniform int TriangleMesh__add(RTCScene scene, const uniform Shape* uniform _this)
{
	const uniform TriangleMesh* uniform this = (const uniform TriangleMesh* uniform) _this;

	uniform unsigned int motion = 1;
	if (this->motion) motion = 2;
	uniform unsigned int mesh = rtcNewTriangleMesh(scene, RTC_GEOMETRY_STATIC, this->numTriangles, this->numPositions, motion);

	uniform RTCTriangle* uniform triangles = (uniform RTCTriangle* uniform) rtcMapBuffer(scene, mesh, RTC_INDEX_BUFFER);
	foreach(j = 0 ... this->numTriangles) {
		const vec4i tri = this->triangle[j];
		triangles[j].v0 = tri.x;
		triangles[j].v1 = tri.y;
		triangles[j].v2 = tri.z;
	}
	rtcUnmapBuffer(scene, mesh, RTC_INDEX_BUFFER);

	uniform RTCVertex* uniform vertices0 = (uniform RTCVertex* uniform) rtcMapBuffer(scene, mesh, RTC_VERTEX_BUFFER0);
	foreach(j = 0 ... this->numPositions) {
		const vec3f p = make_vec3f(this->position[j]);
		vertices0[j].x = p.x;
		vertices0[j].y = p.y;
		vertices0[j].z = p.z;
	}
	rtcUnmapBuffer(scene, mesh, RTC_VERTEX_BUFFER0);

	if (this->motion)
	{
		uniform RTCVertex* uniform vertices1 = (uniform RTCVertex* uniform) rtcMapBuffer(scene, mesh, RTC_VERTEX_BUFFER1);
		foreach(j = 0 ... this->numPositions) {
			const vec3f p = make_vec3f(this->position[j]);
			const vec3f dp = make_vec3f(this->motion[j]);
			vertices1[j].x = p.x + dp.x;
			vertices1[j].y = p.y + dp.y;
			vertices1[j].z = p.z + dp.z;
		}
		rtcUnmapBuffer(scene, mesh, RTC_VERTEX_BUFFER1);
	}

	if (1) {
		//rtcSetIntersectionFilterFunction1(scene, mesh, (RTCFilterFuncUniform)&intersectionFilterMy);
		rtcSetOcclusionFilterFunction(scene, mesh, (uniform RTCFilterFuncVarying)&occlusionFilterMy);
	}
	return mesh;
}

**Comment by svenwoop** [comment]
I just re-checked our intersection_filter tutorial and it works properly. Maybe your occlusion rays do not hit the geometry? The filter function is only invoked if you hit something. Does the intersection filter function work?

Please give us the verbose output of you application, by passing "verbose=2" to rtcNewDevice.

**Comment by rt258** [comment]
@svenwoop 
Thanks for your comment.
I have tried the intersection_filter in embree 2.12 as well, and it works fine. 
However, the original code of embree renderer 2.3.2 does not have the filter feature. Thus, I try to implement the occlusion filter in embree renderer 2.3.2. And the code I attached was from embreee renderer but not embree 2.12. The C++ code and ISPC code are quite similar, but only C++ works properly.
I have spent several days to locate the problem, but can't find out why.
I guess this is because I forget to include some configuration head files?

**Comment by rt258** [comment]
Dear @svenwoop,

I have attached both verbose output of c++ and ispc:
[C++.txt](https://github.com/embree/embree-renderer/files/610802/C.txt)
[ispc.txt](https://github.com/embree/embree-renderer/files/610803/ispc.txt)


The verbose output of ISPC version shows **an error**:
Embree: Invalid operation, (you have to use rtcSetOcclusionFilterFunctionN in st
ream mode)
Embree: Invalid operation, (you have to use rtcSetOcclusionFilterFunctionN in st
ream mode)
 
However, in ISPC mode , the scene IS initialized in non-stream mode:

void Scene__Constructor(uniform Scene* uniform this)
{
  LOG(print("Scene__Constructor\n"));
  RefCount__Constructor(&this->base,Scene__Destructor);

  this->numAllLights = 0;
  this->allLights = uniform new UniformLightPtr[16*1024]; // FIMXE: hardcoded constant
  for (uniform int i=0; i<16*1024; i++) this->allLights[i] = NULL;

  this->numEnvLights = 0;
  this->envLights = uniform new UniformEnvLightPtr[16*1024]; // FIXME: hardcoded constant
  for (uniform int i=0; i<16*1024; i++) this->envLights[i] = NULL;

  this->numInstances = 0;
  this->instances = uniform new UniformInstancePtr [1024*1024]; // FIXME: hardcoded constant
  this->handle2id = uniform new uint[1024*1024];
  this->id2handle = uniform new uint[1024*1024];
  for (uniform int i=0; i<1024*1024; i++) {
    this->instances[i] = NULL;
    this->handle2id[i] = -1;
    this->id2handle[i] = -1;
  }

  this->handle = rtcNewScene(RTC_SCENE_STATIC,RTC_INTERSECT_VARYING);
}

**Comment by rt258** [comment]
@svenwoop 
Thanks for your advice of using verbose=2.
We have figured this out by comment this line:
  //aflags |= (uniform RTCAlgorithmFlags)(1 << 5); /* ray stream interface */

This is because, in embree renderer, the rtcNewScene force converted the device into stream mode.

RTCScene rtcNewScene (uniform RTCSceneFlags flags, uniform RTCAlgorithmFlags aflags) 
{  
  if (aflags & RTC_INTERSECT_VARYING) {
    if (sizeof(varying float) == 16)
      aflags = (uniform RTCAlgorithmFlags) ((aflags & ~RTC_INTERSECT_VARYING) | (1 << 1));
    else if (sizeof(varying float) == 32)
      aflags = (uniform RTCAlgorithmFlags) ((aflags & ~RTC_INTERSECT_VARYING) | (1 << 2));
    else if (sizeof(varying float) == 64)
      aflags = (uniform RTCAlgorithmFlags) ((aflags & ~RTC_INTERSECT_VARYING) | (1 << 3));

    //aflags |= (uniform RTCAlgorithmFlags)(1 << 5); /* ray stream interface */
  }
  return ispcNewScene(flags,aflags);
}
