### ISSUE TITLE
Embree renderer is too slow on Haiku

### ISSUE THREAD

**Issue by extrowerk** [embree/embree-renderer#9]
![146695669e1e405c937b895a27e55a67](https://user-images.githubusercontent.com/5569059/32578032-0ac41a5a-c4dc-11e7-9516-b76f97330371.png)

Please make it real-time, thanks!

**Comment by svenwoop** [comment]
It looks like you run only with one thread and maybe even in debug mode? Even on one thread one should expect 3.5fps for the cornell box. There is likely a problem with the treading on Haiku. 

The embree-renderer project is suspended and Haiku anyway not officially supported. Please switch to using the pathtracer of Ospray (www.ospray.org).

**Comment by extrowerk** [comment]
Oh, ok i haven't noticed that. Thanks!

-- Z.

2017.11.09. dátummal, 8:18 időpontban Sven Woop <notifications@github.com> írta:

**Comment by extrowerk** [comment]
@svenwoop : can i still send my patches?
Here is my test-results: https://gist.github.com/extrowerk/7afba8f9dfb8276322677418cd0ec026
